### ISSUE TITLE
input stream was truncated while reading a word

### ISSUE THREAD

**Issue by jurivrljicak** [sjamesr/jfreesane#113]
Hello, from
```

SaneSession.java  

private void initSane() throws IOException {
    // RPC code
    outputStream.write(SaneRpcCode.SANE_NET_INIT);

    // version number
    outputStream.write(SaneWord.forSaneVersion(1, 0, 3));

    // username
    outputStream.write(System.getProperty("user.name"));
    outputStream.flush();

    **inputStream.readWord();**
    inputStream.readWord();
  }
```

I am getting 'input stream was truncated while reading a word' in the highlighted line.
I don't know why this happens, any idea?

Very often I have to plug/unplug the device for it to establish a communication but this time I can't pass through this error. Got stuck in there. 

Using Ubuntu 16.04 LTS and the latest from jfreesane (1.0)

thanks

**Comment by jurivrljicak** [comment]
It's where I am trying to establish the connection.

```
			this.inetAddress = InetAddress.getByName(this.host);
			saneSession = SaneSession.withRemoteSane(inetAddress, port);
```

using Oracle OpenJDK 17.0.2

**Comment by jurivrljicak** [comment]
could this be a hardware issue? I was tending to think that

**Comment by jurivrljicak** [comment]
hmmm, the port is the default one

yes, scanimage -d kds_i900:i900 > output.pnm does work

**Comment by sjamesr** [comment]
On Fri, Mar 15, 2024 at 9:20 AM jurivrljicak ***@***.***>
wrote:

> hmmm, the port is the default one
>
> yes, scanimage -d kds_i900:i900 > output.pnm does work
>
That's not using the sane daemon though, that command is talking to the
scanner directly.

Try something like:

scanimage -d net:localhost:kds_i900:i900

**Comment by jurivrljicak** [comment]
oh, sorry, then I get

$ scanimage -d net:localhost:kds_i900:i900
scanimage: open of device net:localhost:kds_i900:i900 failed: Error during device I/O

**Comment by sjamesr** [comment]
You'll have to set up the sane daemon. Something like
https://help.ubuntu.com/community/SaneDaemonTutorial

**Comment by jurivrljicak** [comment]
yes I don't know, I restarted the sane daemon and started working again,
looks that process dies at anytime and I am unaware.

Sorry for this and thx again

**Comment by 15123309443** [comment]
I've had this happen to me as well

my code:
    InetAddress address = InetAddress.getLocalHost();
    SaneSession saneSession = SaneSession.withRemoteSane(address);
    List<SaneDevice> devices = saneSession.listDevices();

![image](https://github.com/user-attachments/assets/2e36ce88-768a-48d2-8ecf-cf2c4dcb0cc3)

**Comment by tita-tovenaar** [comment]
Good evening all,

When trying to run the following code in Eclipse IDE:

> package test;
> 
> import java.io.IOException;
> import java.net.InetAddress;
> import java.util.List;
> 
> import au.com.southsky.jfreesane.SaneDevice;
> import au.com.southsky.jfreesane.SaneException;
> import au.com.southsky.jfreesane.SaneSession;
> 
> public class SaneTest {
> 
> 	public static void main(String[] args) throws IOException, SaneException {
> 	    InetAddress address = InetAddress.getByName("pi-scan");
> 		System.out.println("Address: " + address);
> 		
> 		SaneSession session = SaneSession.withRemoteSane(address);
> 		System.out.println("Session: " + session);
> 		
> 		List<SaneDevice> devices;
> 		devices = session.listDevices();
> 
> 	}
> 
> }

I get the following error output:

> Address: pi-scan/10.0.0.29
> Session: au.com.southsky.jfreesane.SaneSession@17f052a3
> Exception in thread "main" java.io.IOException: input stream was truncated while reading a word
> 	at au.com.southsky.jfreesane.SaneWord.fromStream(SaneWord.java:43)
> 	at au.com.southsky.jfreesane.SaneInputStream.readWord(SaneInputStream.java:139)
> 	at au.com.southsky.jfreesane.SaneInputStream.readStatus(SaneInputStream.java:135)
> 	at au.com.southsky.jfreesane.SaneInputStream.readDeviceList(SaneInputStream.java:47)
> 	at au.com.southsky.jfreesane.SaneSession.listDevices(SaneSession.java:220)
> 	

What happened? Can you help me? Thanks in advance.

at test.SaneTest.main(SaneTest.java:21)
