### ISSUE TITLE
Class au.com.southsky.jfreesane.SaneSessionTest fails due to "java.lang.AssertionError: Expected test to throw (exception with message a string containing "STATUS_ACCESS_DENIED" and an instance of au.com.southsky.jfreesane.SaneException)"

### ISSUE THREAD

**Issue by krichter722** [sjamesr/jfreesane#43]
During `./gradlew check` `Class au.com.southsky.jfreesane.SaneSessionTest` fails due to `java.lang.AssertionError: Expected test to throw (exception with message a string containing "STATUS_ACCESS_DENIED" and an instance of au.com.southsky.jfreesane.SaneException)`. The stack is:

    java.lang.AssertionError: Expected test to throw (exception with message a string containing "STATUS_ACCESS_DENIED" and an instance of au.com.southsky.jfreesane.SaneException)
	    at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:118)
	    at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:498)
	    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	    at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	    at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.lang.reflect.Method.invoke(Method.java:498)
	    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	    at java.lang.Thread.run(Thread.java:745)

Standard output is:

    Number of options=52
    Scan mode=Gray
    Bit depth=8
    Hand-scanner simulation
    Three-pass simulation [inactive]
    Set the order of frames [inactive]
    Scan resolution
    Scan source=Flatbed
    Select the test picture=Solid black
    Invert endianness [inactive]
    Read limit
    Size of read-limit [inactive]
    Read delay
    Duration of read-delay [inactive]
    Return-value of sane_read=Default
    Loss of pixels per line=0
    Fuzzy parameters
    Use non-blocking IO
    Offer select file descriptor
    Enable test options
    Print options
    Top-left x
    Top-left y
    Bottom-right x
    Bottom-right y
    (1/6) Bool soft select soft detect [inactive]
    (2/6) Bool hard select soft detect [inactive]
    (3/6) Bool hard select [inactive]
    (4/6) Bool soft detect [inactive]
    (5/6) Bool soft select soft detect emulated [inactive]
    (6/6) Bool soft select soft detect auto [inactive]
    (1/6) Int [inactive]
    (2/6) Int constraint range [inactive]
    (3/6) Int constraint word list [inactive]
    (4/6) Int array [inactive]
    (5/6) Int array constraint range [inactive]
    (6/6) Int array constraint word list [inactive]
    (1/3) Fixed [inactive]
    (2/3) Fixed constraint range [inactive]
    (3/3) Fixed constraint word list [inactive]
    (1/3) String [inactive]
    (2/3) String constraint string list [inactive]
    (3/3) String constraint long string list [inactive]
    (1/1) Button [inactive]
    Successfully wrote /tmp/mono-image4540914859303788263.png
    Successfully wrote /tmp/image-Gray-1-Grid4238567796543944756.png
    Successfully wrote /tmp/image-Color-8-Color_pattern3520648899252557732.png
    Successfully wrote /tmp/image-Color-16-Color_pattern656621202493502416.png
    Wrote three-pass test to /tmp/three-pass4565281593701204827.png
    Wrote three-pass test to /tmp/three-pass6961226896446831934.png
    Wrote three-pass test to /tmp/three-pass4663490150488985882.png
    Wrote three-pass test to /tmp/three-pass138852075170770012.png
    Wrote three-pass test to /tmp/three-pass6469570975301994568.png
    Successfully wrote /tmp/image6905594968353086660.png
    We found 44 options
    Option: , Number of options, value type: INT, units: UNIT_NONE
    1
    Option: mode, Scan mode, value type: STRING, units: UNIT_NONE
    1
    Option: depth, Bit depth, value type: INT, units: UNIT_NONE
    1
    Option: hand-scanner, Hand-scanner simulation, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: three-pass, Three-pass simulation, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: three-pass-order, Set the order of frames, value type: STRING, units: UNIT_NONE
    1
    Option: resolution, Scan resolution, value type: FIXED, units: UNIT_DPI
    1
    Option: source, Scan source, value type: STRING, units: UNIT_NONE
    1
    Option: test-picture, Select the test picture, value type: STRING, units: UNIT_NONE
    1
    Option: invert-endianess, Invert endianness, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: read-limit, Read limit, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: read-limit-size, Size of read-limit, value type: INT, units: UNIT_NONE
    1
    Option: read-delay, Read delay, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: read-delay-duration, Duration of read-delay, value type: INT, units: UNIT_MICROSECOND
    1
    Option: read-return-value, Return-value of sane_read, value type: STRING, units: UNIT_NONE
    1
    Option: ppl-loss, Loss of pixels per line, value type: INT, units: UNIT_PIXEL
    1
    Option: fuzzy-parameters, Fuzzy parameters, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: non-blocking, Use non-blocking IO, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: select-fd, Offer select file descriptor, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: enable-test-options, Enable test options, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: print-options, Print options, value type: BUTTON, units: UNIT_NONE
    Option: tl-x, Top-left x, value type: FIXED, units: UNIT_MM
    1
    Option: tl-y, Top-left y, value type: FIXED, units: UNIT_MM
    1
    Option: br-x, Bottom-right x, value type: FIXED, units: UNIT_MM
    1
    Option: br-y, Bottom-right y, value type: FIXED, units: UNIT_MM
    1
    Option: bool-soft-select-soft-detect, (1/6) Bool soft select soft detect, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: bool-hard-select-soft-detect, (2/6) Bool hard select soft detect, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: bool-hard-select, (3/6) Bool hard select, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: bool-soft-detect, (4/6) Bool soft detect, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: bool-soft-select-soft-detect-emulated, (5/6) Bool soft select soft detect emulated, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: bool-soft-select-soft-detect-auto, (6/6) Bool soft select soft detect auto, value type: BOOLEAN, units: UNIT_NONE
    1
    Option: int, (1/6) Int, value type: INT, units: UNIT_NONE
    1
    Option: int-constraint-range, (2/6) Int constraint range, value type: INT, units: UNIT_PIXEL
    1
    Option: int-constraint-word-list, (3/6) Int constraint word list, value type: INT, units: UNIT_BIT
    1
    Option: int-constraint-array, (4/6) Int array, value type: INT, units: UNIT_MM
    6
    Option: int-constraint-array-constraint-range, (5/6) Int array constraint range, value type: INT, units: UNIT_DPI
    6
    Option: int-constraint-array-constraint-word-list, (6/6) Int array constraint word list, value type: INT, units: UNIT_PERCENT
    6
    Option: fixed, (1/3) Fixed, value type: FIXED, units: UNIT_NONE
    1
    Option: fixed-constraint-range, (2/3) Fixed constraint range, value type: FIXED, units: UNIT_MICROSECOND
    1
    Option: fixed-constraint-word-list, (3/3) Fixed constraint word list, value type: FIXED, units: UNIT_NONE
    1
    Option: string, (1/3) String, value type: STRING, units: UNIT_NONE
    1
    Option: string-constraint-string-list, (2/3) String constraint string list, value type: STRING, units: UNIT_NONE
    1
    Option: string-constraint-long-string-list, (3/3) String constraint long string list, value type: STRING, units: UNIT_NONE
    1
    Option: button, (1/1) Button, value type: BUTTON, units: UNIT_NONE

experienced with jfreesane-0.95-39-g284b46c on Ubuntu 16.04 with `[SaneDevice [name=hpaio:/usb/HP_Color_LaserJet_MFP_M476dn?serial=CNB8H415Z5, vendor=Hewlett-Packard, model=HP_Color_LaserJet_MFP_M476dn, type=all-in-one]]`

**Comment by sjamesr** [comment]
This will happen if the test device is not protected by a username and password (see the comments at the top of SaneSessionTest). You can try adding the line

```
testuser:goodpass:test
```

to `/etc/sane.d/saned.users`. I'm open to better suggestions for how to test authentication.

**Comment by krichter722** [comment]
> This will happen if the test device is not protected by a username and password (see the comments at the top of SaneSessionTest). You can try adding the line

>     testuser:goodpass:test

> to /etc/sane.d/saned.users. I'm open to better suggestions for how to test authentication.

Understood. Do you think it's a good idea to skip the involvement of system service and it's configuration, by building a test version of SANE in the source root and make it listen on a random port > 1024 from within `maven`. Would you be up for a PR doing that?

**Comment by sjamesr** [comment]
I'd rather not maintain a fork of SANE (it's big), but perhaps we could check in the minimum set of config files and run `/usr/sbin/saned` with that config on a random port. Looks like setting the `SANE_CONFIG_DIR` is the way to go there.

Another solution might be to download and build SANE if `saned` isn't on the PATH. To make the tests run faster, we'd have to cache that. This will also put additional dependencies on the machine running JFreeSane (like, it won't work on Windows).
